# Generated by Django 3.2.9 on 2022-12-04 16:46

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('artist', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('url', models.TextField()),
                ('content', models.TextField()),
            ],
            bases=(models.Model, api.models.CreatedUpdatedMixin),
        ),
        migrations.CreateModel(
            name='Songbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('session_key', models.CharField(max_length=20, unique=True)),
                ('current_song_timestamp', models.DateTimeField()),
                ('max_active_songs', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=40)),
                ('last_nav_action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('is_noodle_mode', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, api.models.CreatedUpdatedMixin),
        ),
        migrations.CreateModel(
            name='SongEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song')),
                ('songbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.songbook')),
            ],
            bases=(models.Model, api.models.CreatedUpdatedMixin),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='api_song_artist_d3ca78_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='api_song_title_7b5a5c_idx'),
        ),
    ]
