# Generated by Django 3.2.9 on 2022-12-03 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('artist', models.CharField(db_index=True, max_length=40)),
                ('album', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=400)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Songbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField()),
                ('session_key', models.CharField(max_length=20, unique=True)),
                ('current_song_timestamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=40)),
                ('album', models.CharField(max_length=40)),
                ('play_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.song')),
                ('songbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.songbook')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='songbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.songbook'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='api_song_artist_d3ca78_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album'], name='api_song_album_52ac1c_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['title'], name='api_song_title_7b5a5c_idx'),
        ),
    ]
