# Generated by Django 3.2.16 on 2022-12-18 15:54

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.RemoveIndex(
            model_name="song",
            name="api_song_artist_d3ca78_idx",
        ),
        migrations.RemoveIndex(
            model_name="song",
            name="api_song_title_7b5a5c_idx",
        ),
        migrations.AddIndex(
            model_name="song",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["artist"], name="api_song_artist_d37ec0_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="api_song_title_823081_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="songentry",
            constraint=models.UniqueConstraint(
                fields=("songbook", "song"), name="unique songbook entry"
            ),
        ),
    ]
