# Generated by Django 3.2.16 on 2022-12-15 23:58

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='api_song_artist_d3ca78_idx',
        ),
        migrations.RemoveIndex(
            model_name='song',
            name='api_song_title_7b5a5c_idx',
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('artist', 'title', config='english'), name='search_vector_idx'),
        ),
        migrations.AddConstraint(
            model_name='songentry',
            constraint=models.UniqueConstraint(fields=('songbook', 'song'), name='unique songbook entry'),
        ),
    ]
