# Generated by Django 3.2.16 on 2022-12-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_search_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='songentry',
            name='unique songbook entry',
        ),
        migrations.AddConstraint(
            model_name='songentry',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('songbook', 'song'), name='unique songbook entry'),
        ),
    ]
