# Generated by Django 3.2.16 on 2022-12-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fix_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
