# Generated by Django 3.2.16 on 2022-12-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('url',), name='unique song entry'),
        ),
    ]
