# Generated by Django 3.2.16 on 2022-12-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221223_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='songbook',
            name='songs',
            field=models.ManyToManyField(related_name='songboooks', through='api.SongEntry', to='api.Song'),
        ),
    ]
