# Generated by Django 3.2.16 on 2022-12-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_songbook_songs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songbook',
            name='current_song_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='songbook',
            name='session_key',
            field=models.CharField(max_length=20),
        ),
    ]
