# Generated by Django 3.2.16 on 2023-01-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_song_content'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='song',
            name='unique song entry',
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('url',), name='unique song url'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('artist', 'title'), name='unique song title and artist'),
        ),
    ]
