# Generated by Django 3.2.16 on 2023-01-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230122_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
