# Generated by Django 3.2.16 on 2023-01-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_add_rating_and_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="capo",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="songentry",
            name="is_flagged",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
