# Generated by Django 3.2.16 on 2023-01-26 18:16

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_capo_and_is_flagged'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='api_song_artist_d37ec0_gin',
        ),
        migrations.RemoveIndex(
            model_name='song',
            name='api_song_title_823081_gin',
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(fields=['artist'], name='song_artist_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='song',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='song_title_gin_index', opclasses=['gin_trgm_ops']),
        ),
    ]
