# Generated by Django 3.2.18 on 2023-03-17 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_fix_gin_indexes'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='songbook',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('session_key',), name='unique songbook session key'),
        ),
    ]
