# Generated by Django 3.2.19 on 2023-05-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_songbook_memberships'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted__isnull', True)), fields=('songbook', 'user'), name='unique membership entry'),
        ),
    ]
