# Generated by Django 3.2.19 on 2023-05-29 22:25

from django.db import migrations, models

def migrate_to_random_session_keys():
    Songbook = apps.get_model("api", "Songbook")
    for songbook in Songbook.objects.all():
        songbook.session_key = Songbook._generate_session_key()
        songbook.Save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_membership_unique membership entry'),
    ]

    operations = [
        migrations.RunPython(migrate_to_random_session_keys, migrations.RunPython.noop)
    ]
