# Generated by Django 3.2.19 on 2023-05-29 22:25

from django.db import migrations
from django.utils.crypto import get_random_string


def migrate_to_random_session_keys(apps, schema_editor):
    Songbook = apps.get_model("api", "Songbook")
    for songbook in Songbook.objects.all():
        songbook.session_key = get_random_string(length=4).upper()
        songbook.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_userprofile"),
    ]

    operations = [
        migrations.RunPython(migrate_to_random_session_keys, migrations.RunPython.noop)
    ]
