# Generated by Django 3.2.19 on 2023-05-29 22:25

import random
import string

from django.db import migrations


def migrate_to_random_session_keys(apps, schema_editor):
    Songbook = apps.get_model("api", "Songbook")
    for songbook in Songbook.objects.all():
        songbook.session_key = "".join(
            random.choice(string.ascii_uppercase) for _ in range(4)
        )
        songbook.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_userprofile"),
    ]

    operations = [
        migrations.RunPython(migrate_to_random_session_keys, migrations.RunPython.noop)
    ]
