# Generated by Django 3.2.19 on 2023-06-03 23:08

from django.db import migrations, models

import api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_migrate_to_random_session_keys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songbook",
            name="session_key",
            field=models.CharField(
                blank=True,
                default=api.models._generate_session_key,
                max_length=4,
            ),
        ),
    ]
