# Generated by Django 3.2.19 on 2023-06-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_song_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='columns_to_display',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_showing_chords',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
