# Generated by Django 3.2.20 on 2023-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_userprofile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='songbook',
            name='theme',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
