# Generated by Django 3.2.20 on 2023-11-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
