# Generated by Django 3.2.20 on 2023-11-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20231124_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_ID',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
