# Generated by Django 3.2.20 on 2023-12-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20231128_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='songbook',
            name='action_verb',
            field=models.CharField(default='DANCE', max_length=8),
        ),
    ]
