# Generated by Django 3.2.20 on 2024-12-24 16:45

from django.db import migrations


class Migration(migrations.Migration):

    def remove_soft_deleted_memberships(apps, schema_editor):
        Membership = apps.get_model('api', 'Membership')
        Membership.objects.filter(deleted__isnull=False).delete()

    dependencies = [
        ('api', '0032_add_songbook_memo'),
    ]

    operations = [migrations.RunPython(remove_soft_deleted_memberships, migrations.RunPython.noop)
    ]
