# Generated by Django 3.2.20 on 2024-12-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_soft_deleted_memberships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='deleted_by_cascade',
        ),
    ]
