# Generated by Django 3.2.20 on 2024-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_disable_soft_delete_for_memberships'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique membership entry',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('songbook', 'user'), name='unique membership entry'),
        ),
    ]
