# Generated by Django 5.2.13 on 2026-05-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_songbookuserposition"),
    ]

    operations = [
        migrations.AddField(
            model_name="songbook",
            name="current_song_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="songbookuserposition",
            name="current_song_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="songentry",
            name="position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
