# Generated by Django 5.2.13 on 2026-05-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_populate_position_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="songbook",
            name="current_song_timestamp",
        ),
        migrations.RemoveField(
            model_name="songbookuserposition",
            name="current_song_timestamp",
        ),
        migrations.AlterField(
            model_name="songbook",
            name="current_song_position",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="songbookuserposition",
            name="current_song_position",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name="songentry",
            name="position",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
